import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Text } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { mswApiHost } from "@/mocks/apiHost";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState<any>([]);

  const getTest = async () => {
    await axios.get(
      `${mswApiHost}/test`, {
      params: {
        path: "getTest"
      }})
      .then((res) => {
        console.log(res.data);
        setData(res.data);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  const config = {
    headers: { "Content-Type": "application/json" },
    withCredentials: true,
  };

  const postTest = async () => {
    await axios
      .post(
        `${mswApiHost}/test`,
        JSON.stringify({
          path: "postTest",
          id: "1234",
          name: "lee",
          country: "ko",
          lang: "react"
      }),
      config
      )
      .then((res) => {
        console.log(res.data);
        setData(res.data);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  useEffect(() => {
    getTest();
  }, []);

  return (
    <>
      <Head>
        <title>Wonderers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <Text fontSize="md" mb="50px">
            Welcome, We are
          </Text>
          <Image
            className={styles.logo}
            src="/logo.svg"
            alt="Next.js Logo"
            width={400}
            height={70}
            priority
          />
          <Button mt="50px" colorScheme="blue" onClick={postTest}>
            Button
          </Button>

          <div>
            {data[0] && data[0].id}
          </div>
        </div>
      </main>
    </>
  );
}